sched: Re-Introduce BORE CPU Scheduler (4.2.0)
BORE (Burst-Oriented Response Enhancer) CPU Scheduler 4.2.0

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.19-bore
--
fix issues and adapt to 4.14 accordingly

../kernel/sysctl.c:174:13: error: redefinition of 'three' with a different type: 'uint' (aka 'unsigned int') vs 'int'
  174 | static uint three          = 3;
      |             ^
../kernel/sysctl.c:132:27: note: previous definition is here
  132 | static int __maybe_unused three = 3;
      |                           ^
1 error generated.
--> guiard
static int __maybe_unused three = 3;

../kernel/sched/fair.c:9139:25: error: too few arguments to function call, expected 2, have 1
 9139 |         rq_clock_skip_update(rq);
      |         ~~~~~~~~~~~~~~~~~~~~   ^

--> restore original
rq_clock_skip_update(rq, true);

../kernel/sched/fair.c:5491:6: error: use of undeclared identifier 'task_sleep'
 5491 |         if (task_sleep) {
      |             ^
--> add
int task_sleep = flags & DEQUEUE_SLEEP;

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.19-bore

0001-linux4.19.y-bore4.2.0.patch
0002-constgran-vanilla-max.patch